### ISSUE TITLE
SDL2 support on macOS

### ISSUE THREAD

**Issue by parasyte** [parasyte/pixels#47]
There are many crates for interfacing with SDL2. There is only one that also uses `raw_window_handle` and that's [`beryllium`](https://crates.io/crates/beryllium).

When I attempted to port the `minimal-winit` example to SDL2 with `beryllium`, I ran into a showstopper where the `raw_window_handle` impl is not able to provide an `NSView` on macOS, and `wgpu`/`gfx` doesn't try to get the default contentView from the NSWindow. So it sees a NULL pointer and panics with `window does not have a valid contentView`.

I could workaround this issue by making the example depend on `cocoa`, at the expense of adding code that shouldn't be in the example anyway. Another option is building a crate specifically for transforming a `raw_window_handle` into a `raw_window_handle` with an `NSView`. 😐

**Comment by parasyte** [comment]
Fixed by #60 (Thanks @lovesegfault!)

**Comment by fzzr-** [comment]
Unfortunately it isn't fixed for me.
I just tried [minimal-sdl2 example][] and it panicked with `window does not have a valid contentView`.

My env versions:
- OS: macOS 10.15.7 (19H2)
- Xcode: 11.7 (xcode-select: 2373)
- SDL2: 2.0.12 (also 2.0.0)


<details><summary>Full log</summary>
<pre><code>
cd minimal-sdl2
cargo run
...
thread 'main' panicked at 'window does not have a valid contentView', /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.6.5/src/lib.rs:391:13
stack backtrace:
   0:        0x102b03fd4 - std::backtrace_rs::backtrace::libunwind::trace::hd4e4f36eb9f0f866
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x102b03fd4 - std::backtrace_rs::backtrace::trace_unsynchronized::hddd9cf7e61567951
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102b03fd4 - std::sys_common::backtrace::_print_fmt::hf0df20706c8d0efd
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x102b03fd4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hddf67b5e68ee5eac
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x102b21f20 - core::fmt::write::hae6418d3f135b639
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/fmt/mod.rs:1078:17
   5:        0x102b01636 - std::io::Write::write_fmt::h822c37b1fbb805d3
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/io/mod.rs:1519:15
   6:        0x102b05cf9 - std::sys_common::backtrace::_print::hf8d765f57ebaea59
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x102b05cf9 - std::sys_common::backtrace::print::h4405042f17c9e5df
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x102b05cf9 - std::panicking::default_hook::{{closure}}::hb8c76ec6b2b5fec2
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:208:50
   9:        0x102b05880 - std::panicking::default_hook::h9520f36dd50be056
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:225:9
  10:        0x102b0637b - std::panicking::rust_panic_with_hook::hbb70e1d25c7381a9
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:591:17
  11:        0x102aab577 - std::panicking::begin_panic::{{closure}}::h3d517ab75ea18d18
                               at /Users/ak/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
  12:        0x102aa8e58 - std::sys_common::backtrace::__rust_end_short_backtrace::hc0d31a0b7abd10e3
                               at /Users/ak/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x102b321d7 - std::panicking::begin_panic::h13246faca81ee5cb
                               at /Users/ak/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
  14:        0x1026cd942 - gfx_backend_metal::Instance::create_from_nsview::h5eadad20febeb160
                               at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.6.5/src/lib.rs:391:13
  15:        0x1026d07f7 - gfx_backend_metal::Instance::create_surface_from_nsview::h64ad6556a64e3e4e
                               at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.6.5/src/lib.rs:444:18
  16:        0x102120453 - <gfx_backend_metal::Instance as gfx_hal::Instance<gfx_backend_metal::Backend>>::create_surface::h69fcc8eeca24dcc5
                               at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.6.5/src/lib.rs:293:20
  17:        0x1021207b0 - wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::instance_create_surface::{{closure}}::h52c64f5333b514fa
                               at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.6.5/src/instance.rs:342:38
  18:        0x1021287a3 - core::option::Option<T>::and_then::hefe02259bbb06bc9
                               at /Users/ak/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:692:24
  19:        0x1021212ea - wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::instance_create_surface::h430dbb04a74c85b7
                               at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.6.5/src/instance.rs:340:21
  20:        0x1021249c5 - <wgpu::backend::direct::Context as wgpu::Context>::instance_create_surface::hcc12d450f7c8cfe5
                               at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:542:9
  21:        0x102122afa - wgpu::Instance::create_surface::h4eaa9e7500043b82
                               at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/lib.rs:1315:17
  22:        0x1021275d0 - pixels::builder::PixelsBuilder<W>::build::h6c6c7bb364d2c1a2
                               at /Users/ak/Developer/Projects/pixels/src/builder.rs:173:32
  23:        0x1021229b7 - pixels::Pixels::new::ha2b93d77752eb177
                               at /Users/ak/Developer/Projects/pixels/src/lib.rs:182:9
  24:        0x102126a4c - minimal_sdl2::main::h6d1a6c08144311ea
                               at /Users/ak/Developer/Projects/pixels/examples/minimal-sdl2/src/main.rs:30:9
  25:        0x10212310e - core::ops::function::FnOnce::call_once::hf4dcbee5bdf1ac2f
                               at /Users/ak/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  26:        0x102120ce1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7fd403fa1512a8b8
                               at /Users/ak/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  27:        0x102120d84 - std::rt::lang_start::{{closure}}::h111b86bc075bea6b
                               at /Users/ak/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  28:        0x102b066f4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4ab201f754b12ec0
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/ops/function.rs:259:13
  29:        0x102b066f4 - std::panicking::try::do_call::h2d40bab4a9c2dc4b
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:379:40
  30:        0x102b066f4 - std::panicking::try::he14232182da07291
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:343:19
  31:        0x102b066f4 - std::panic::catch_unwind::ha032e0ba57e1000e
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panic.rs:396:14
  32:        0x102b066f4 - std::rt::lang_start_internal::hebea83fb59fe572e
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/rt.rs:51:25
  33:        0x102120d61 - std::rt::lang_start::h27ad99d24ca98058
                               at /Users/ak/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  34:        0x102127322 - _main
</code></pre>
</details>


_minimal-winit example works fine._


[minimal-sdl2 example]: https://github.com/parasyte/pixels/tree/0a893d6eff5661950fb039c77f65dd2d8201d460/examples/minimal-sdl2

**Comment by fzzr-** [comment]
ping @parasyte

**Comment by lovesegfault** [comment]
> ping @parasyte

Is it _really_ necessary to ping someone less than one hour after you've posted your issue? :/ 

People already get pinged for new comments in issues they participate in.

**Comment by parasyte** [comment]
This did get broken with `wgpu` 0.6, but it's still not our bug. The most we can do here is raise awareness.

Also FWIW there is a deeper issue here that is being tracked in https://github.com/gfx-rs/wgpu-rs/issues/674 I suspect fixing that issue is the first step. So I would like to direct any attention there.

**Comment by fzzr-** [comment]
Thank you. Well, so I think it would be great to reopen this issue.

**Comment by parasyte** [comment]
Is there anything in particular that would be accomplished by reopening this issue, apart from tracking purposes?
